#Joke Telling Program..
print("What is the name of the first electricity detective?")
input()
print("Sherlock Ohms")
print()
print("Where does bad light end up?")
input()
print("In a prism")
print()
print(" How many theoretical physicists specializing in general relativity does it take to change a light bulb?")
input()
print("Two. One to hold the bulb and one to rotate the universe.")
print()
print("Why can’t you trust an atom?")
input()
print("They make up everything")
print()
print("What do you get when you mix sulfur, tungsten, and silver?")
input()
print("SWAG")
print()
print(" Why did Erwin Schrödinger, Paul Dirac and Wolfgang Pauli work in very small garages?")
input()
print("Because they were quantum mechanics.")
print()
print("What is a physicist’s favourite food?")
input()
print("Fission Chips!")
print()
